### ISSUE TITLE
Register a new release?

### ISSUE THREAD

**Issue by sethaxen** [cscherrer/SampleChainsDynamicHMC.jl#20]
The compats of a number of dependencies and the version number of this package were incremented in a87cbe9, but no release was registered. Should it have been?

**Comment by cscherrer** [comment]
Yes, let's get all dependencies caught up, then figure out whether that's a breaking change

**Comment by cscherrer** [comment]
Just checked this locally, looks like that commit was enough. I've tagged a new release:
https://github.com/JuliaRegistries/General/pull/61025
